# @package task
_target_: lightning_transformers.task.huggingface.multiple_choice.MultipleChoiceTransformer
downstream_model_type: transformers.AutoModelForMultipleChoice
backbone: ${backbone}
optimizer: ${optimizer}
scheduler: ${scheduler}
