# @package task
_target_: lightning_transformers.task.huggingface.question_answering.QuestionAnsweringTransformer
backbone:
  downstream_model_type: transformers.AutoModelForQuestionAnswering
  pretrained_model_name_or_path: bert-base-cased
optimizer: ${optimizer}
scheduler: ${scheduler}