defaults: # for loading the default config
  - training: default
  - trainer: default
  - scheduler: linear_schedule_with_warmup
  - optimizer: adamw
  - tokenizer: huggingface
  - model: huggingface
  - logger: tchaton

dataset: ???
experiment_name: ${now:%Y-%m-%d}_${now:%H-%M-%S}
log: False
ignore_warnings: True