defaults: # for loading the default config
  - training: default
  - trainer: default
  - scheduler: linear_schedule_with_warmup
  - optimizer: adamw
  - tokenizer: huggingface
  - model: huggingface

model: ???
dataset: ???