_target_: lightning_transformers.task.vision.dalle.datasets.CIFARTransformerDataModule
data_dir: ~/cifar/
# torch data-loader specific arguments
batch_size: ${training.batch_size}
num_workers: ${training.num_workers}
